GET https://localhost:7055/User/GetSecret
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJzdHJpbmciLCJQYXNzd29yZCI6InN0cmluZyIsImV4cCI6MTY4NzU2OTEzNywiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NzA1NSIsImF1ZCI6Imh0dHBzOi8vbG9jYWxob3N0OjcwNTUifQ.sw_Ov7ktRQJrDmHZ2N4TVFAkaOFeWAzjlamhu6NiWqQ